apiVersion: v1
kind: Namespace
metadata:
  name: design90-infrastructure
  labels:
    project: design90
    access-method: "port-forward"
    created-by: "design90-implementation"
  annotations:
    description: "design90 infrastructure services namespace"
    contact: "design90-team"
